services:
  auth:
    build: ./gass-auth
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - DATABASE_HOST=mongodb
  server:
    build: ./gass-server
    ports:
      - 8181:8181
    depends_on:
      - mongodb
    environment:
      - DATABASE_HOST=mongodb
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - auth
      - server
  mongodb:
    # image: mongo:latest
    image: mongo:4.4.19
    ports:
      - 8282:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
    driver: local